#!/usr/bin/env bash
#Creates the file ontaining its PID/Displays To infinity and beyond indefinitely/Create  the kill command/eceiving a SIGINT signal/Deletes the file
mkdir var
mkdir /var/run
echo $BASHPID > /var/run/holbertonscript.pid
while true
do
echo "To infinity and beyond"
trap "echo I hate the kill command && rm /var/run/holbertonscript.pid && exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid && exit" SIGQUIT
done
