#!/usr/bin/env bash
# This script is displaying displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration.
counter="0"
while [ $counter -le 9 ]
do
	if [ $counter -eq 3 ];
	then
		echo "bad luck"
	elif [ $counter -eq 7 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
